name: AntiXrayHeuristics
version: ${project.version}
main: es.mithrandircraft.antixrayheuristics.AntiXrayHeuristics
api-version: 1.13
authors: [__Mithrandir__]
description: An heuristically based monitor designed to stop and/or punish xray usage.
website: www.mithrandircraft.es
commands:
  AXH:
    description: Can reload the plugin if specified with reload parameter.
    aliases: [AntiXrayHeuristics]
  XraySuspicion:
    description: Shows your own, or specified player's suspicion level. (Development intended)
  ResetXraySuspicion:
    description: Resets your own, or specified player's suspicion level back to 0.