name: AntiXrayHeuristics
version: ${project.version}
main: es.mithrandircraft.antixrayheuristics.AntiXrayHeuristics
api-version: 1.17
authors: [__Mithrandir__]
description: An heuristically based monitor designed to stop and/or punish xray usage.
website: www.mithrandircraft.es
commands:
  AntiXrayHeuristics:
    description: Does nothing on it's own. Requires further arguments.
    aliases: axh
  AXH Reload:
    description: Will reload the plugin's configuration when specified as axh argument.
  AXH ResetSuspicion:
    description: Resets your own, or specified player's suspicion level back to 0.
  AXH Xrayer:
    description: Handles a player as xrayer. Should be used on someone you are sure is xraying, or for testing.
  AXH Vault:
    description: Opens the Xray Vault GUI showing players registered as xrayers, and, if configured, confiscated inventories when specified as axh argument.
  AXH Absolve:
    description: Removes xrayer from xrayer vault and restores belongings.
  AXH Purge:
    description: Removes xrayer from xrayer vault.
  AXH Suspicion:
    description: TEST