name: AntiXrayHeuristics
version: 1.1.2
main: es.mithrandircraft.antixrayheuristics.AntiXrayHeuristics
api-version: 1.13
authors: [__Mithrandir__]
description: An heuristically based monitor designed to stop and/or punish xray usage.
website: www.mithrandircraft.es
commands:
  AntiXrayHeuristics:
    description: Does nothing on it's own. Requires further arguments.
    aliases: axh
  AXH Reload:
    description: Will reload the plugin's configuration when specified as axh argument.
    aliases: r
#  AXH Suspicion:
#    description: Shows your own, or specified player's suspicion level when specified as axh argument. (Development intended)
#    aliases: s
  AXH ResetSuspicion:
    description: Resets your own, or specified player's suspicion level back to 0.
    aliases: rs
  AXH Xrayer:
    description: Handles a player as xrayer. Should be used on someone you are sure is xraying, or for testing.
    aliases: x
  AXH Vault:
    description: Opens the Xray Vault GUI showing players registered as xrayers, and, if configured, confiscated inventories when specified as axh argument.
    aliases: v
  AXH Absolve:
    description: Removes xrayer from xrayer vault and restores belongings.
    aliases: a
  AXH Purge:
    description: Removes xrayer from xrayer vault.
    aliases: p